# Generated by Django 3.0.6 on 2020-06-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=3, verbose_name='Sınıf')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('number', models.IntegerField(verbose_name='Numara')),
                ('answer', models.CharField(max_length=50, verbose_name='Cevap')),
                ('answer_key', models.CharField(max_length=100, verbose_name='Cevap Anahtarı')),
                ('quiz_name', models.CharField(max_length=100, verbose_name='Sınavın Adı')),
                ('quiz_result', models.IntegerField(blank=True, null=True, verbose_name='Aldığı Puan')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('yanlislar', models.CharField(max_length=120, verbose_name='Yanlışları')),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100, verbose_name='Sınav Adı')),
                ('answer_key', models.CharField(max_length=100, verbose_name='Cevap Anahtarı')),
                ('quiz_file', models.FileField(upload_to='', verbose_name='Sınav Dosyası')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
            ],
        ),
    ]
