# Generated by Django 3.0.6 on 2020-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=3, verbose_name='Sınıfı')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('number', models.IntegerField(verbose_name='Numara')),
                ('answer', models.CharField(max_length=50, verbose_name='Cevap')),
                ('answer_key', models.CharField(max_length=100, verbose_name='Cevap Anahtarı')),
                ('quiz_name', models.CharField(max_length=100, verbose_name='Sınavın Adı')),
                ('quiz_result', models.IntegerField(blank=True, null=True, verbose_name='Aldığı Puan')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
            ],
        ),
        migrations.RenameField(
            model_name='quizmodel',
            old_name='ansver_key',
            new_name='answer_key',
        ),
    ]
