# Generated by Django 3.0.6 on 2020-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numara',
            field=models.CharField(max_length=5, verbose_name='Numarası'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sinif',
            field=models.CharField(max_length=3, verbose_name='Sınıfı'),
        ),
    ]
