# Generated by Django 3.0.6 on 2020-06-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizModel',
        ),
    ]
